# Generated by Django 3.2.9 on 2021-12-06 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=20)),
                ('meeting_time', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('course_type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('lab_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lab_name', models.CharField(max_length=20)),
                ('has_grader', models.BooleanField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='email', max_length=20)),
                ('password', models.CharField(default='email', max_length=20)),
                ('email', models.EmailField(default='email', max_length=20)),
                ('home_address', models.CharField(default='"101 W. Wisconsin Ave, Milwaukee, WI 53203"', max_length=20)),
                ('role', models.IntegerField(default=1)),
                ('phone', models.CharField(default='', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='LabTAJunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAInformation.lab')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAInformation.user')),
            ],
        ),
        migrations.CreateModel(
            name='LabCourseJunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAInformation.course')),
                ('lab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAInformation.lab')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAInformation.user'),
        ),
    ]
