# Generated by Django 4.0 on 2021-12-19 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TAInformation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='has_grader',
        ),
    ]
